environments:
  example:
    environment_variables:
      EXAMPLE_DEPLOYMENT: testing
    pipelines:
      - build-ruby-docker-image
pipelines:
  build-ruby-docker-image:
    group: default
    materials:
      ror:  # this is the name of material
        # says about type of material and url at once
        git: git@github.com:chaomao/ror.git
        branch: 2018wh
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              tasks:
               - exec:
                    command: bash
                    arguments:
                      - "-e "
                      - "./devops/docker-images/build_base_ruby_images.sh"
